model_type: "cnn"          # or "cnn"
batch_size: 128
epochs: 10
learning_rate: 0.001

device: "cpu"             # cpu / mps / auto

log_wandb: true
wandb_project: "mnist_autoencoders"
wandb_run_name: "cnn_run"  # or cnn_run